import { Providers } from "./components/Provider";
import Navbar from "./components/Navbar";
import "./globals.css";
import { Inter } from "next/font/google";
import { Oswald } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Space Travel",
  description: "Generated by Goodness dev",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <Navbar />
          {children}
        </Providers>
      </body>
    </html>
  );
}
